services:
  mongodb:
    image: mongo:7
    container_name: kaas-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  etcd:
    image: bitnami/etcd:latest
    container_name: kaas-etcd
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"

volumes:
  mongo_data:
